name: dbt12

profile: dbt12

seed-paths: ["seeds"]
model-paths: ["models"]
macro-paths: ["macros"]
clean-targets:
  - "target"
  - "dbt_packages"

seeds:
  # Builds seeds into '<your_schema_name>_raw'
  dbt12:
    +schema: raw

models:
  dbt12:
    # Materialize staging models as views, and marts as tables
    gold:
      +materialized: view
      +schema: gold
    silver:
      +materialized: table
      +schema: silver
